### PR TITLE
removed one "would" of two

### PR DESCRIPTION
**Pull request by horst-n**

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Now why would would we want to do that?

**Comment by horst-n** [comment]
I really can't recall why I have committed this, but I would would suggest to think about it once more. :)

**Comment by ryancramerdesign** [comment]
I would would if I could could.

**Comment by ryancramerdesign** [comment]
Okay i'm just playing here. :) I think you missed my double would would joke in the first one. Thanks for finding this I will fix it it.

**Comment by NicoKnoll** [comment]
:)

**Comment by horst-n** [comment]
Yes you should should. 

Okay, I haven't missed the double would joke, see my answere: "..but I would would ..."
:)

**Comment by LostKobrakai** [comment]
@horst-n Could you close this, if the issue is fixed?

**Pull request closed without merging**
