### PR TITLE
Improve support for SVG. Fix issue #802 - SVGs without width/height attributes. Also add support for SVG sanitizing via customizable whitelist.

### PR DESCRIPTION
**Pull request by adrianbj**
Sorry about the whitespace changes in these files. Must be something I have set in ST3. I am sure you know, but it's easy to hide whitespace differences by appending ?w=1 to the Github URL.

I am sure you'll have some better ideas on how to achieve some of these things, but this seems to be working well. I'll leave some more comments about what I have done under Issue #802 .

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Adrian I'm working on integration of this and came up with a few questions: 

Line 162 and 163:
```````
$this->imageInfo['width'] = (int) $a->width > 0 ? (int) $a->width : '100%';
$this->imageInfo['height'] = (int) $a->height > 0 ? (int) $a->height : '100%';
```````
It looks like it gets converted to an integer (with the "%") either way. So was wondering about the percentage here. I'm confused since dimensions in imageInfo are meant to represent pixel dimensions not percentages. Are there any other parts in the code that depend on these values representing percentages?

Regarding the whitelist: having it configurable as JSON with the field settings (interactive) seems like overkill? Not to mention a lot of bytes to store with the field. I'm thinking this should be a site-wide setting rather than a field-by-field setting, and a $config->svgWhitelist setting that one can override in their config.php file, rather than configured interactively (especially since it's already in code, JSON). But just wanted to make sure I wasn't missing anything important about the configuration intentions here?

Regarding the option to refuse or sanitize the SVG: why not just standardize on one or the other? Or if we were to make it configurable, I would think it should also be an overall setting rather than a field-by-field setting. Again, I don't use SVGs very often so I might be missing something. But I'd like to keep it as simple and secure as possible. I prefer the strategy of refusing anything that isn't valid, rather than trying to sanitize it, but maybe SVGs are a unique case. 

Why is the SVG handling done in InputfieldFile rather than InputfieldImage? Doesn't InputfieldImage seem like the more appropriate place for this, since InputfieldFile is supposed to be general purpose/anything goes, and InputfieldImage is supposed to be specific to the needs of images?

Lastly, I can't help but wonder if we should weigh the benefits to having a separate InputfieldImageSVG module that contains all of this, since they are so fundamentally different than bitmap based images. What do you think? Thanks for your work on this. Looks like great things for PW's SVG support regardless of what strategy we use to implement.

**Comment by adrianbj** [comment]
Thanks for getting this implemented.

Regarding the 100% issue - I couldn't figure out a better way to deal with this, but the key issue is that if no dimensions are set in the SVG then PW declares the image invalid here: https://github.com/ryancramerdesign/ProcessWire/blob/676458407bd530b69b50c6ef2f44cf16e4ef4449/wire/modules/Inputfield/InputfieldImage/InputfieldImage.module#L65

If there is no value set, we are defining it specifically to 100% - I don't think that is changed (or converted to an integer) after that. This approach means that the image won't be resized too 100px when being displayed (which would happen if we converted to an integer) but will still validate as an image because it has a width set. If you haven't read it in a while, then perhaps glance at my initial comments on this: https://github.com/ryancramerdesign/ProcessWire/issues/802#issuecomment-66542125

As for being able to configure the whitelist - I was trying to give the most flexibility, the reason being is that SVG can be purely vector, but it can also include embedded raster images, and a variety of raster effects. I personally have situations where I want to allow these in some situations, but not in others. I have an SVG image library that is tied in with svgedit and that requires even more restrictions because of elements that svgedit doesn't yet support. I also have a script to automatically convert SVG "contact sheets" into Adobe Illustrator symbol library palettes, which also requires some restrictions. But on other parts of the site, it's ok to allow these elements since they are simply being displayed on the front-end of the site. I am probably a very unique case though :)

I thought it useful to be able to choose to sanitize or refuse - either way should result in a safe uploaded file. I guess it depends on the scenario. If you are just looking to make the file safe, then you won't be removing the ability to embed raster images etc, in which case sanitizing is appropriate as it could simply remove a rogue line of javascript from the file and continue - nice for the uploader! But if you are trying to prevent raster elements, then refusing the image makes more sense because the error message lets the uploader know what elements weren't allowed and lets them modify their image before uploading again. This ties back to the whitelist and why I made it configurable at the field level.

I went with InputfieldFile because I was trying to ensure security for PW. There is nothing stopping someone uploading an SVG to a file field and displaying it on the front-end, even if this is not the intended purpose of the field fieldtype. On this topic, I wonder if PW should have a more general XML sanitizer script to handle all relevant uploaded files?

I don't think a separate InputfieldImageSVG wouldn't really work well for me - given that it is so simple these days to display an SVG on a site with  I feel like users will want to mix and match image types in one image field. Again I might be an unusual case but lots of my scientific websites allow the editors to upload photos or diagrams/illustrations into the same field that the template file code then renders. The quality of diagrams is always better with SVG when sizing up/down. In the case of a very complex diagram with a large filesize I will rasterize it automatically with http://modules.processwire.com/modules/image-rasterizer/ to make for faster admin and front-end rendering.

Sorry I hope that helps rather than confuses. Please let me know if there is anything I can clarify.

**Comment by adrianbj** [comment]
What about maybe storing the whitelist data in the sanitizer config settings (or in config.php) but with an option to override if the field specific whitelist field is populated, rather than the current behavior where the field is automatically populated for each file/image field?

Would that be cleaner?

**Comment by adrianbj** [comment]
Ryan - I just noticed that the Guthub address for the SVG sanitizer class I that I modified has changed from:
```
https://github.com/alister-/SVG-Sanitizer
```
to:
https://github.com/alnorris/SVG-Sanitizer

Which means that we should also change this:
```
SVG Sanitizer by Alister Norris: https://github.com/alister-
```

to:
```
SVG Sanitizer by Alister Norris: https://github.com/alnorris/
```

I think I mentioned elsewhere, but as a reminder I did change this code a fair bit - there were some missing SVG elements, but also there were some issues with the sanitize method - I think it was missing some nested elements or something - might be worth you doing a quick diff on them to see the changes I made, just in case you can see any optimizations I overlooked.

**Comment by ryancramerdesign** [comment]
Adrian, what I ended up doing here is adding the ability to validate any type of file by way of a new module interface. That way one can choose what kind of files they want to validate via modules. It also keeps InputfieldFile out of the business of file-type specific validation, which is something it isn't meant for (though InputfieldImage is). But now that it can delegate that ability to plugins/modules for those that want it, I feel like that gives us the most flexibility without adding file-type specific code to a non-file-type specific module. Over time I also think it'll be genuinely useful for lots of different file types, and reduce the need for many potential InputfieldFile derived modules. 

I took your MarkupSvgSanitizer module and converted it to a FileValidator module called [FileValidatorSvgSanitizer](https://github.com/ryancramerdesign/FileValidatorSvgSanitizer). I uploaded it to a repo so that you can fork/download/clone it, and then then it's yours if you are agreeable to maintaining it? Let me know when you've got it and I'll remove from my account. 

Maybe in time most sites will be using SVGs and SVG sanitization is something that should be part of the core (and thus that module part of the core), but I'm a little reluctant to go there since I'm not hearing about SVGs from many (so far it's just you). :) I also don't want to manage the burden or build the expectation that PW validates all kind of different files on it's own. PW's admin is designed to be a trusted user environment after all. But what I would like to do is if they add a note about SVG support in InputfieldImage's config settings that recommends installation of FileValidatorSvgSanitizer using using SVGs. That's because I think you are right that sanitization/validation of this type is probably a good idea for anyone using it, so want to be sure they are aware of the sanitization/validation capability they can install with this type. Let me know if this sounds good to you or if you have any other thoughts. Thanks.

**Comment by ryancramerdesign** [comment]
> I just noticed that the Guthub address for the SVG sanitizer class I that I modified has changed from:

Btw, the FileValidatorSvgSanitizer module uses your updated class (that was in the PR), not the one from the alister- or alnorris repo.

**Comment by adrianbj** [comment]
Yeah, I love the approach you've take. I can see lots of uses for this. We should start with a general XML validator next.

I have forked the new module - thanks. Since you are removing from your account, I'll set it up as a new repo, rather than a fork of yours.

Should I submit this to the modules directory today so we have a working example for the new FileValidatorModule class, since you'll be blogging about it today?

I see you made it possible to provide a custom whitelist with a fallback to the default - thanks for that. 

Thanks again for your work on this.

**Comment by adrianbj** [comment]
Should we go with FileValidatorSvgSanitizer or simply FileValidatorSvg ?

Are all validators going to be sanitizers or do you think it is necessary to make the distinction as you named it with the "Sanitizer" on the end?

**Comment by ryancramerdesign** [comment]
Adrian, that would be great if you have time to put it on your GitHub and
add to the modules directory today, and I'll definitely link to them in the
blog post.

The custom overrides I put as $config settings because [especially] the
whitelist I thought was maybe just a bit too much data to store in the DB
(which gets retrieved on every request). Though it's not a big deal and I'm
probably overthinking that. But I also figured the people interested in
modifying SVG whitelists by way of hand editing JSON are probably more than
comfortable with editing a site config file, and might even prefer that to
interactive. Plus, that gives them the option to using either PHP array or
JSON strings, whatever they prefer, which is something we couldn't have
supported in an interactive textarea field (at least not without an evil
err... eval).

**Comment by ryancramerdesign** [comment]
I don't know for sure since the SVG is the only one that exists yet, but am
thinking that many validators would not also be sanitizers. It seems like
sanitization will most likely to confined to text/markup-based formats like
SVG, XML, HTML, etc. Most binary file types likely can't be sanitized, so
are either valid or not valid. However, I don't think it really matters as
far as the module name goes. Use whatever you prefer. I mainly used
SvgSanitizer to stay consistent wit the naming of your Markup module.

**Pull request closed without merging**
