### PR TITLE
Add feature to create schema if it does not exist

### PR DESCRIPTION
**Pull request by plauclair**

### CODE REVIEW

**Comment by plauclair** [comment]
@ryancramerdesign is that something you're interested in pulling? Let me know if you'd like some modifications, I'll happily make them. Cheers!

**Comment by ryancramerdesign** [comment]
I think I'm struggling with the terminology. It looks like it adds a
feature to create the database as part of the install (which I like, would
be great for localhost/dev installs where user often has create database
access), but with using "schema" as the terminology, so then I thought
maybe I didn't fully understand. Or it's possible I just don't have my
terminology right. But when I think "schema" I translate to "organization
of columns in table or tables in a database". The installer already creates
the schema, by the definition I understand. So while I think I might be
missing something, if the PR does what I'm thinking it does (allow for the
option of creating the database) then I'll definitely add it–and thank you
for the idea! Though will probably make it more transparent in terms of
terminology, or just leave out the terminology entirely (silently create
the specified database if it doesn't already exist). But let  me know if
there is another aspect to this that I haven't yet understood.

On Wed, Mar 4, 2015 at 6:10 PM, Pierre-Luc Auclair <notifications@github.com

**Comment by teppokoivula** [comment]
Was wondering about the same thing when this popped up. "SCHEMA" is a synonym to "DATABASE" in MySQL since 5.0.2, so "CREATE SCHEMA" translates to "CREATE DATABASE" for old school MySQL users ;)

**Comment by plauclair** [comment]
My bad! Yes in MySQL, database === schema. http://dev.mysql.com/doc/refman/5.6/en/glossary.html#glos_schema

I can fix the terminology and update the pull request, or if you prefer to do it go ahead. Just let me know which way you prefer! :)

**Comment by plauclair** [comment]
This is done, closing PR.

**Pull request closed without merging**
