### PR TITLE
Link to tabs with hash

### PR DESCRIPTION
**Pull request by Da-Fecto**
- Added the ability to focus on a certain tab by using a hash in the URL.
- Added the ability to use [link title](#has-tag) in field descriptions to link to a tab.

for Content, Children & Settings use #content #children #settings behind the urls,
or [content](#content) etc... in field descriptions.

for FieldsetTabOpen use  [field title](#field_name) in field descriptions.

tnx, Martijn

### CODE REVIEW

**Comment by NicoKnoll** [comment]
Why not closed if completed? :)

**Comment by boundaryfunctions** [comment]
Has this one ever been merged?

**Comment by isellsoap** [comment]
@Da-Fecto Can this be closed?

**Comment by ryancramerdesign** [comment]
I don't recall if this one was specifically merged or not, but know that we
do have hash support for tabs, which I think was added in 2.4.

On Wed, Aug 19, 2015 at 5:05 AM, Francesco Schwarz <notifications@github.com

**Pull request closed without merging**
