### PR TITLE
Fixes sort for subvalues

### PR DESCRIPTION
**Pull request by esrch**
There seemed to be a bug when trying to sort by a subvalue of a FieldtypePage, e.g., $pages->find("template=product, sort=brand.title"). I was getting an error "Unknown column '_sort_page_brand_title.title' in 'order clause'". The change fixes this, but I am not absolutely certain that it covers all bases, so someone with better knowledge about the table structure should have a look...

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Thanks esrch, this is a nice addition. I have brought this in and am testing this week. I'll be committing to dev soon after rewriting to make sure I understand it, and after passing the PW selector tests. But so far it looks like you've added support for something we didn't previously support, so this is a very nice addition for sure. Thanks for your work here!

**Comment by esrch** [comment]
Hi Ryan, thanks, that's great! I actually thought it was a bug... :-) So I'm glad to read that I could contribute a new feature! I hope that the code will work correctly.

**Comment by plauclair** [comment]
This is pretty amazing @esrch ! I've been meaning to have a look at it myself for some time now and been using different tricks around this, glad it's now supported! :+1:

**Comment by esrch** [comment]
I'm glad that I could help :-) I really needed this feature, and that's the great thing about open source: you can participate to make the software better!

**Pull request closed without merging**
