### PR TITLE
Implemented multi-language page name handling for PagePathHistory module

### PR DESCRIPTION
**Pull request by bfncs**
The core module `PagePathHistory` didn't handle [multi-language URLs/page names](http://processwire.com/api/multi-language-support/multi-language-urls/) implemented by the core module `LanguageSupportPageNames` until now. I [already described this](https://processwire.com/talk/topic/9342-pagepathhistory-with-multi-language-page-names/) in greater detail in the forum.

This patch adds language-awareness for  `PagePathHistory`.

### CODE REVIEW

**Comment by boundaryfunctions** [comment]
I just see this after opening the pull request: in my patch the file has been converted from tab- to space-indentation. Sorry, I didn't give this enough thought, please just let me know if this needs to be reverted in order to accept this PR. To make evaluating the patch a bit easier, it's possible to see the [diff with whitespace ignored](https://github.com/boundaryfunctions/ProcessWire/commit/beaae233a22f16b4a718ae3b551f364ce15303e4?w=false).

**Comment by ryancramerdesign** [comment]
Great work solving this one! I know this is not an easy thing to do (I gave up once before). That being said, I've got a lot to absorb here and understand, so it'll take me a little longer to get through this one. I go through PR's line by line so that I can understand and support them, and sometimes make other core adjustments to support them when there is an opportunity to do so. But wanted to let you know this is appreciated and this is now on my todo.

**Comment by boundaryfunctions** [comment]
Hi Ryan,

thanks a lot for your kind words! I've also been doubting about my knowledge of Processwire while working on the module, but then on the other hand it was very rewarding in terms of learning about a lot of core implementation details along the way. This was also what motivated me to [question the current architecture of hooks](https://processwire.com/talk/topic/9356-the-future-of-hooks/) on the forums, actually. While it probably isn't the most elegant solution now, it should get the job done.

Please take all time needed to get this into core, I will be glad if it makes it there. If someone is in desperate need of this functionality in the meanwhile, it is not a big deal to use this module as a userspace module (basically just rename the class to `PagePathHistoryLanguage`, install it as usual in `site/modules/PagePathHistory` and use it instead of the core `PagePathHistory` module, see the  [standalone version](https://gist.github.com/boundaryfunctions/4f52979da5ff7bf67d8a)).

Thanks a lot and keep up the great work.

**Comment by LostKobrakai** [comment]
There isn't even the need to rename it. See this: http://processwire.com/blog/posts/processwire-core-updates-2.5.14/

**Comment by boundaryfunctions** [comment]
*Processwire - already having implemented that feature since just before you started thinking of it*

That's great news, thanks for pointing it out, @LostKobrakai.

**Comment by bfncs** [comment]
This [has been implemented in `3.0.7`](https://processwire.com/blog/posts/processwire-3.0.7-expands-field-rendering-page-path-history-and-more/#page-path-history-now-multi-language) and can be closed. 

Keep up the great work, Ryan!

**Pull request closed without merging**
