### PR TITLE
Do not forward a send request to socket, when the resultcode of that …

### PR DESCRIPTION
**Pull request by ruudalberts**
…request is a known http success code

### CODE REVIEW

**Comment by ruudalberts** [comment]
Stumbled upon this when I did a 3rd party URL forward on a FormBuilder form. The URL did not return a response, and therefore the request was fired again (but through socket), resulting in e-mails being sent twice. "Fixed" it by echo-ing a random string, but would rather see this sorted more fashionably :)

**Comment by ryancramerdesign** [comment]
Thanks @ruudalberts – good idea. I have added this.

**Comment by LostKobrakai** [comment]
@ruudalberts This has been added. Could you please close the PR?

**Comment by matjazpotocnik** [comment]
It would be good to modify documentation that method returns not only false on failure and string on success, but also true! And that happen when timeout (default is 4.5 sec) occurs.

`@return bool|string False on failure or string of contents received on success.`

**Pull request closed without merging**
