### PR TITLE
correct spelling for 'htaccess'

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Thanks, good find, fixed!

**Comment by vsopvsop** [comment]
I don't want your thanks or appreciation.

What prevented you from merging PR directly and giving me credit?

**Comment by LostKobrakai** [comment]
@vsopvsop As mentioned by Ryan on the forums it's his best practice to implement changes on his own to ensure he fully understands them if he needs to supply support for them. I see that this shouldn't be the case here, but there's also not much credit to be given here in terms of responsibility of a feature or such. 
Anyways this has been fixed. Could you please close the PR?

**Comment by mikerockett** [comment]
@vsopvsop Wow, that is quite rude. Suggestion: think before your comment, please.

**Comment by isellsoap** [comment]
@vsopvsop Please watch your language. Thanks.

**Pull request closed without merging**
