### PR TITLE
Add support for removing fields from templates in the field's Actions tab.

### PR DESCRIPTION
**Pull request by adrianbj**
Hi Ryan - I see from your notes that you were contemplating implementing this, so here is a quick attempt - I think it works quite well. The user has to check a box next to each template to confirm removal of the field from that template, so hopefully it is "safe" enough.

### CODE REVIEW

**Comment by adrianbj** [comment]
PS sorry not sure what happened, but it looks like I ended up doing this PR to the master dev instead of dev. Hopefully you can fairly easily do a diff on my changes from your dev version of this file.

**Comment by adrianbj** [comment]
Here are some sequential screenshots of the process

Initial status of fields in templates:
screen shot 2015-02-04 at 3 35 27 pm

Choose to remove the field from basic-page and add it to blog:
screen shot 2015-02-04 at 3 35 43 pm

Confirm removal of field from basic-page and choose location for it to be added to blog:
screen shot 2015-02-04 at 3 36 12 pm

Final screen showing updated status of fields in templates:
screen shot 2015-02-04 at 3 36 40 pm

**Comment by adrianbj** [comment]
Along with all the fixes from yesterday, I just added some strong warning text (see updated screenshot above) to mention the data loss issues etc with deleting the field from the selected templates - the wording is basically stolen from the text that displays when deleting a field from ProcessTemplate, so I think that makes it as obvious and safe as that now.

I think this will be very handy during site development when refactoring things - it can be tedious to delete an obsolete field from many templates via the GUI.

**Comment by apeisa** [comment]
Looks very clean and huge timesaver!

**Comment by ryancramerdesign** [comment]
Thanks for your work on this Adrian. I ended up wanting to do a few things differently, so used your PR as the map rather than directly as the code. But hope I didn't miss anything key–please let me know. The main thing is that I wanted to avoid the redirect to executeModifyTemplates occurring on every single field save, and this is one of the reasons this remove feature didn't originally accompany the add feature… you know how checkbox fields can be. But I found a way around that. Also wanted to make it highlight the amount(s) of data that was stored, and/or going to be destroyed by removal (pages for Fieldtypes or pages + rows for FieldtypeMulti fields). Plus some other little things like making sure all the additions were taken place before any of the removals (since removals are a little more expensive operation), and making the text labels contextual to the scenario (i.e. not showing a strong warning message if there isn't any data present in the field being deleted, and things of that sort). None of this is to take anything away from your PR–you did a great job, and thank you for the contribution! I pretty much always re-code anything that goes into existing core files, for my own understanding and ability to support, and to identify potential issues and optimizations that I might miss otherwise.

**Comment by adrianbj** [comment]
No problem - I totally agree about the issue with the redirect to executeModifyTemplates occurring on every single field save. Hopefully you saw my comment about the redirect back to the edit screen if no changes were made being a hack - I really should have put a little more thought into refactoring to avoid that - I like your solution to the problem!

**Pull request closed without merging**
