### PR TITLE
Added Save + Edit Next ability

### PR DESCRIPTION
**Pull request by CaelanStewart**
Hi,

I opened a feature request, but because it was trivial to implement, I forked your repo and made the necessary changes.

### CODE REVIEW

**Comment by LostKobrakai** [comment]
I certainly do not want to discourage your efforts, but I think this should be rather be solved by making the dropdown options hookable instead of adding every new needed functionality into the core.

**Comment by CaelanStewart** [comment]
I agree, I probably will make a small plugin to add that option if it is made hookable. And I do plan on making further contributions to ProcessWire in future, since I've used it for quite a few sites now, I feel like I want to give something back.

**Comment by LostKobrakai** [comment]
Then I'd suggest reading this one: https://processwire.com/api/coding-style-guide/

**Comment by CaelanStewart** [comment]
Thank you for that, it's lucky that my personal code style is practically identical to what is listed.

**Comment by ryancramerdesign** [comment]
Thanks guys, we've now got this feature in the core.

**Pull request closed without merging**
