### PR TITLE
getQueryHasParent() avoid subquery 

### PR DESCRIPTION
**Pull request by pine3ree**
...when pages.parent_id = $parent_id

I am not sure the extra () are needed, just added it to be on the safe side

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Thanks, looks good–I will add it and test it out.

**Comment by isellsoap** [comment]
@pine3ree Can this PR be closed? If yes, please feel free to do so. :-)

**Comment by pine3ree** [comment]
@isellsoap 
Hello, better ask Ryan. My PR was about a simple db query modification (i think it was merged long time ago). I am not sure where the rest of it came from. :-) kind regards.

**Comment by LostKobrakai** [comment]
@isellsoap Would you be so kind to close this PR? It's marked as completed and all the commit notices are more confusing than it would be useful to let this PR stay open.

**Comment by isellsoap** [comment]
@LostKobrakai I can't, I'm didn't open the PR. :-)

**Comment by LostKobrakai** [comment]
@isellsoap Sorry, tagged the wrong one :) 
@pine3ree Could you please read my comment above.

**Comment by pine3ree** [comment]
sure, regards

**Pull request closed without merging**
