### PR TITLE
Added option to reject images exceeding the Max Dimensions setting

### PR DESCRIPTION
**Pull request by JanRomero**
Also added "px" as the units in error messages and changed x to × (&times;). Existing translations should not be affected.

Hope I got everything right.

Cheers

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
Thanks @JanRomero, I have added this PR and it will appear in today's commits.

**Comment by isellsoap** [comment]
@JanRomero Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!

**Comment by isellsoap** [comment]
@JanRomero ?

**Comment by JanRomero** [comment]
Oh, sorry. Sure, yeah!

**Pull request closed without merging**
